
---

- name:               Create Postgres Security Group
  ec2_group:
    name:             "Postgres"
    description:      "Allow Comms to and from postgres"
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    rules:
      - proto:        "tcp"
        ports:
        - 5432
        cidr_ip:      "{{subnet_1_cidr }}"

- name:               Create Zabbix Security Group
  ec2_group:
    name:             "Zabbix"
    description:      "Allow Comms to and from zabbix server and agents"
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    rules:
      - proto:        "tcp"
        ports:
        - 10050
        - 10051
        cidr_ip:      "{{subnet_1_cidr }}"

- name:               Create Mgmt Security Group
  ec2_group:
    name:             "Mgmt"
    description:      "Allow ssh"
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    rules:
      - proto:        "tcp"
        ports:
        - 22
        cidr_ip:      "{{my_ip}}/32"
