
---

- name:               Create Postgres Security Group
  ec2_group:
    name:             "Postgres"
    description:      "Allow Comms to and from postgres"
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    rules:
      - proto:        "tcp"
        ports:
        - 5432
        cidr_ip:      "{{subnet_1_cidr }}"
  register:           sec_group_postgres

- name: print stuff
  debug: var=sec_group_postgres

- name:               set postgres security group fact
  set_fact:
    postgres_sec_group: "{{ sec_group_postgres.group_id }}"

- name:               Create Zabbix Security Group
  ec2_group:
    name:             "Zabbix"
    description:      "Allow Comms to and from zabbix server and agents"
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    rules:
      - proto:        "tcp"
        ports:
        - 10050
        - 10051
        cidr_ip:      "{{subnet_1_cidr }}"
  register:           sec_group_zabbix

- name:               set zabbix security group fact
  set_fact:
    zabbix_sec_group: "{{ sec_group_zabbix.group_id }}"

- name:               Create Mgmt Security Group
  ec2_group:
    name:             "Mgmt"
    description:      "Allow ssh"
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    rules:
      - proto:        "tcp"
        ports:
        - 22
        - 80
        - 443
        - 4440
        cidr_ip:      "{{my_ip}}/32"
  register:           sec_group_mgmt

- name:               set mgmt security group fact
  set_fact:
    mgmt_sec_group: "{{ sec_group_mgmt.group_id }}"

