
---
 - name: upgrade and install postgres packages
   become: yes
   apt: 
     name: "{{ packages }}"
   vars:
     packages:
     - postgresql
     - libpq-dev
     - python-psycopg2
   when: inventory_hostname in groups['postgres']
   #with_items: "{{ postgres_instance.instances }}"

#  - name: ensure database is created
#    become: yes
#    become_user: postgres
#    postgresql_db: name={{dbname}}
#    when: inventory_hostname in groups['postgres']
#
#  - name: ensure user has access to database
#    become: yes
#    become_user: postgres
#    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
#    when: inventory_hostname in groups['postgres']
#
#  - name: ensure user does not have unnecessary privilege
#    become: yes
#    become_user: postgres
#    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
#  
#  - name: ensure no other user can access the database

